#!/usr/bin/env node
/**
 * USDA dataset ingestion script (Implementation Plan, Phase 0).
 *
 * Converts a CSV of nutrition rows into a SQL migration that seeds the
 * `usda_foods` table (schema: Backend & Database Schema doc, 2.3).
 *
 * Usage:
 *   node scripts/ingest-usda.mjs [inputCsv] [outputSql]
 *
 * Defaults:
 *   inputCsv  = data/usda_seed.csv        (curated ~130-item starter set)
 *   outputSql = src-tauri/src/db/sql/0002_usda_seed.sql
 *
 * To load the FULL USDA FoodData Central dataset (~400k rows) instead of the
 * starter set, download a CSV export from https://fdc.nal.usda.gov/download-datasets
 * and re-map its columns to match the header this script expects:
 *   fdc_id,description,category,calories_per_100g,protein_g_per_100g,
 *   carbs_g_per_100g,fat_g_per_100g,fiber_g_per_100g
 * then re-run this script against that file. Because a migration this large
 * would bloat the compiled binary, prefer chunked INSERTs (already done below)
 * and consider raising the migration version number rather than editing
 * 0001/0002 in place once the app has shipped.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

const inputPath = resolve(repoRoot, process.argv[2] ?? "data/usda_seed.csv");
const outputPath = resolve(
  repoRoot,
  process.argv[3] ?? "src-tauri/src/db/sql/0002_usda_seed.sql"
);

const EXPECTED_COLUMNS = [
  "fdc_id",
  "description",
  "category",
  "calories_per_100g",
  "protein_g_per_100g",
  "carbs_g_per_100g",
  "fat_g_per_100g",
  "fiber_g_per_100g",
];

const NUMERIC_COLUMNS = new Set([
  "fdc_id",
  "calories_per_100g",
  "protein_g_per_100g",
  "carbs_g_per_100g",
  "fat_g_per_100g",
  "fiber_g_per_100g",
]);

/** Minimal RFC-4180 CSV parser: handles quoted fields, embedded commas, and "" escapes. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    const next = text[i + 1];

    if (inQuotes) {
      if (c === '"' && next === '"') {
        field += '"';
        i++;
      } else if (c === '"') {
        inQuotes = false;
      } else {
        field += c;
      }
      continue;
    }

    if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n" || c === "\r") {
      if (c === "\r" && next === "\n") i++;
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else {
      field += c;
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows.filter((r) => r.length > 1 || r[0] !== "");
}

function sqlEscapeString(value) {
  return `'${value.replace(/'/g, "''")}'`;
}

function toSqlLiteral(column, rawValue) {
  const value = rawValue.trim();
  if (NUMERIC_COLUMNS.has(column)) {
    if (value === "") return "NULL";
    const num = Number(value);
    if (Number.isNaN(num)) {
      throw new Error(`Expected numeric value for column "${column}", got "${value}"`);
    }
    return String(num);
  }
  if (value === "") return "NULL";
  return sqlEscapeString(value);
}

function main() {
  const csvText = readFileSync(inputPath, "utf-8");
  const rows = parseCsv(csvText);
  const header = rows[0].map((h) => h.trim());

  for (const col of EXPECTED_COLUMNS) {
    if (!header.includes(col)) {
      throw new Error(
        `Input CSV is missing required column "${col}". Expected header: ${EXPECTED_COLUMNS.join(",")}`
      );
    }
  }

  const dataRows = rows.slice(1).filter((r) => r.some((cell) => cell.trim() !== ""));

  const valueTuples = dataRows.map((r) => {
    const byCol = Object.fromEntries(header.map((h, i) => [h, r[i] ?? ""]));
    const literals = EXPECTED_COLUMNS.map((col) => toSqlLiteral(col, byCol[col] ?? ""));
    return `(${literals.join(", ")})`;
  });

  const CHUNK_SIZE = 200;
  const statements = [];
  for (let i = 0; i < valueTuples.length; i += CHUNK_SIZE) {
    const chunk = valueTuples.slice(i, i + CHUNK_SIZE);
    statements.push(
      `INSERT INTO usda_foods (${EXPECTED_COLUMNS.join(", ")})\nVALUES\n  ${chunk.join(",\n  ")};`
    );
  }

  const sql = [
    `-- Generated by scripts/ingest-usda.mjs from ${process.argv[2] ?? "data/usda_seed.csv"}`,
    `-- Row count: ${dataRows.length}`,
    `-- Regenerate with: node scripts/ingest-usda.mjs`,
    "",
    statements.join("\n\n"),
    "",
  ].join("\n");

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, sql, "utf-8");

  console.log(`Ingested ${dataRows.length} USDA food rows.`);
  console.log(`Wrote SQL migration: ${outputPath}`);
}

main();
